using System.Collections.Generic;

namespace Kingdee.Zitn.Project.Code.models
{
    /// <summary>
    /// 企业微信用户映射（中文姓名 → 企微用户名）
    /// </summary>
    public static class WeComUserMapping
    {
        /// <summary>
        /// 用户映射字典（中文姓名 → 企微用户名）
        /// </summary>
        public static readonly IReadOnlyDictionary<string, string> UserMap = new Dictionary<string, string>
{
    { "刘军", "LiuJun" },
    { "张吉先", "XiaoZhang" },
    { "彭寿龙", "PengShouLong" },
    { "马敏锋", "MaMinFeng" },
    { "薛冬", "XueDong" },
    { "徐雨秀", "Xu" },
    { "崔文墨", "CuiWenMo" },
    { "谷志鹏", "GuZhiPeng" },
    { "韩超", "HanChao" },
    { "郝豫璇", "HaoYuXuan" },
    { "胡强林", "HuQiangLin" },
    { "蒋孟杨", "JiangMengYang" },
    { "刘永瑜", "LiuYongYu" },
    { "史晓阳", "ShiXiaoYang" },
    { "田雨", "TianYu" },
    { "王莹", "WangYing" },
    { "吴玲芳", "zitn--WuLingFang" },
    { "武闻凡", "WuWenFan" },
    { "徐卫平", "XuWeiPing" },
    { "杨婷", "YangTing" },
    { "袁迎发", "YuanYingFa" },
    { "张锐", "ZhangRui" },
    { "张义梓", "ZhangYiZi" },
    { "张云龙", "ZhangYunLong1" },
    { "赵加乐", "ZhaoJiaLe" },
    { "赵颖", "ZhaoYing" },
    { "李阳（男）", "LiYang_1" },
    { "王一鸣", "WangYiMing" },
    { "陈轲", "ChenKe_1" },
    { "陈亚林", "ChenYaLin" },
    { "郭俊", "GuoJun" },
    { "贾云云", "JiaYunYun" },
    { "刘国伟", "LiuGuoWei" },
    { "王新宇", "WangXinYu" },
    { "杨晶", "YangJing" },
    { "杨青", "YangQing" },
    { "张蕾", "ZhangLei" },
    { "张蕊", "ZhangRui_1" },
    { "赵纪委", "ZhaoJiWei" },
    { "钟林洁", "ZhongLinJie" },
    { "周萍", "ZhouPing" },
    { "刘旭", "LiuXu" },
    { "施锐元", "ShiRuiYuan" },
    { "王建勇", "WangJianYong" },
    { "黄玉娟", "HuangYuJuan" },
    { "李盛梅", "LiShengMei" },
    { "刘欣", "LiuXin1" },
    { "王晓伟", "WangXiaoWei1" },
    { "程翠鹏", "ChengCuiPeng" },
    { "程金晶", "ChengJinJing" },
    { "陈顺平", "ChenShunPing" },
    { "杜言", "DuYan" },
    { "鞠宸浩", "JuChenHao" },
    { "刘同富", "LiuTongFu" },
    { "李言军", "LiYanJun" },
    { "潘城林", "PanChengLin" },
    { "邱兆飞", "QiuZhaoFei" },
    { "沈宇", "ShenYu" },
    { "孙伟", "SunWei" },
    { "孙玉达", "Da" },
    { "孙中将", "SunZhongJiang" },
    { "汪康胜", "ShuoLeYeBaiShuo" },
    { "王小锐", "WangXiaoRui" },
    { "王昱芗", "WangYuXiang" },
    { "武渝翔", "WuYuXiang" },
    { "许天赐", "XuTianCi" },
    { "张传庆", "ZhangChuanQing" },
    { "张建功", "ZhangJianGong" },
    { "张腾飞", "ZhangTengFei" },
    { "张妤", "ZhangYu" },
    { "郑笃全", "ZhengDuQuan" },
    { "崔甜甜", "CuiTianTian" },
    { "丁长春", "DingChangChun" },
    { "巩乃成", "GongNaiCheng" },
    { "侯炳先", "HouBingXian" },
    { "接乘浩", "JieChengHao" },
    { "孔丽", "KongLi" },
    { "李方方", "FangFang" },
    { "刘晓乐", "LiuXiaoLe" },
    { "慕丹萍", "MuDanPing" },
    { "皮冬冬", "PiDongDong" },
    { "任远航", "RenYuanHang" },
    { "王昆", "WangKun01" },
    { "王帅翔", "WangShuaiXiang" },
    { "王晓雷", "WangXiaoLei" },
    { "吴学森", "WuXueSen" },
    { "薛铭鑫", "XueMingXin" },
    { "杨春东", "YangChunDong" },
    { "于洋", "YuYang" },
    { "曾国凤", "ZengGuoFeng" },
    { "赵峰晨", "ZhaoFengChen" },
    { "唐贵", "TangGui" },
    { "冯永智", "FengYongZhi" },
    { "付士民", "FuShiMin" },
    { "郭世超", "GuoShiChao" },
    { "胡青杉", "HuQingShan" },
    { "胡新超", "HuXinChao" },
    { "李涛", "LiTao" },
    { "刘雪倩", "LiuXueQian" },
    { "李义翔", "LiYiXiang" },
    { "逄金洁", "PangJinJie" },
    { "任大江", "RenDaJiang" },
    { "张国栋", "ZhangGuoDong" },
    { "祝志远", "ZhuZhiYuan" },
    { "马亚锋", "MaYaFeng" },
    { "范如雪", "FanRuXue" },
    { "惠浩", "HuiHao" },
    { "梁磊", "LiangLei" },
    { "李小姣", "LiXiaoJiao" },
    { "王若宇", "WangRuoYu" },
    { "魏成林", "WeiChengLin" },
    { "姚晓娜", "YaoXiaoNa" },
    { "于邦志", "YuBangZhi" },
    { "杜婉儿", "DuWanEr" },
    { "范帅", "FanShuai" },
    { "袁明", "YuanMing" },
    { "樊涛", "FanTao" },
    { "丁明康", "DingMingKang" },
    { "胡杰", "HuJie" },
    { "卢飞", "LuFei" },
    { "王轲", "SiPaiKeDeLingCheng" },
    { "张京伟", "ZhangJingWei" },
    { "周超聪", "ZhouChaoCong" },
    { "周星", "ZhouXing" },
    { "周宇翔", "ZhouYuXiang" },
    { "王冲", "WangChong1" },
    { "董金汇", "DongJinHui" },
    { "董英鑫", "DongYingXin" },
    { "付裕", "FuYu" },
    { "高东显", "GaoDongXian" },
    { "韩德康", "HanDeKang" },
    { "贺敬蕊", "HeJingRui" },
    { "江苗苗", "JiangMiaoMiao" },
    { "李厚振", "LiHouZhen" },
    { "李画云", "LiHuaYun" },
    { "刘浩冉", "LiuHaoRan" },
    { "刘杰", "LiuJie" },
    { "李艳红", "LiYanHong" },
    { "岂红艳", "QiHongYan" },
    { "王红枚", "WangHongMei" },
    { "王华", "WangHua" },
    { "王利", "WangLi" },
    { "王鹏飞", "WangPengFei" },
    { "王新", "WangXin_1" },
    { "王绪霞", "WangXuXia" },
    { "许圣凯", "XuShengKai" },
    { "袁国辉", "YuanGuoHui" },
    { "郑玉凤", "PiaoXue" },
    { "刘群", "LiuQun" },
    { "徐江燕", "XuJiangYan" },
    { "谭兴宇", "TanXingYu" },
    { "徐铭璐", "XuMingLu" },
    { "姚新帅", "YaoXinShuai" },
    { "张程鑫", "ZhangChengXin" },
    { "张雅芝", "ZhangYaZhi" },
    { "郑泽浩", "ZhengZeHao" },
    { "周韶芳", "ZhouShaoFang" },
    { "刘涛", "LiuLao" },
    { "李旭晨", "LiXuChen" },
    { "肖晓峰", "XiaoXiaoFeng" },
    { "刘颖", "LiuYing" },
    { "石云", "ShiYun" },
    { "臧梦缘", "ZangMengYuan" },
    { "张慧", "ZhangHui" },
    { "朱培康", "ZhuPeiKang" },
    { "郭庆", "GuoQing" },
    { "何俊义", "HeJunYi" },
    { "李姝宜", "LiShuYi" },
    { "王若歆", "WangRuoXin" },
    { "王舒丙", "WangShuBing1" },
    { "于宝阳", "ChiXiaoYan1" },
    { "朱艳玲", "ZhuYanLing1" },
    { "陈传昀", "ChenChuanYun" },
    { "邱显圣", "QiuXianSheng" },
    { "孙祥飞", "SunXiangFei" },
    { "朱东婷", "ZhuDongTing" },
    { "訾豫熙", "ZiYuXi" },
    { "朱英才", "ZhuYingCai01" },
    { "宋佳", "SongJia" },
    { "罗家栋", "LuoJiaDong" },
    { "邓昌雪", "AJiu" },
    { "包木彩", "BaoMuCai" },
    { "冯书涵", "FengShuHan" },
    { "韩立素", "HanLiSu" },
    { "韩章懿", "HanZhangYi" },
    { "何中梅", "HeZhongMei" },
    { "黄俊杰", "HuangJunJie" },
    { "惠荣", "HuiRong" },
    { "贾立超", "JiaLiChao" },
    { "姜欣", "JiangXin" },
    { "焦宝玉", "JiaoBaoYu" },
    { "矫蒙丽", "JiaoMengLi" },
    { "矫帅启", "JiaoShuaiQi" },
    { "纪苗苗", "JiMiaoMiao" },
    { "梁雅文", "LiangYaWen" },
    { "李金胜", "LiJinSheng" },
    { "林欢", "LinHuan" },
    { "刘欢", "HuanKuaiDeXiao" },
    { "刘建萍", "LiuJianPing" },
    { "刘路路", "LiuLuLu" },
    { "刘洋", "LiuYang" },
    { "李友浩", "LiYouHao" },
    { "卢庆梅", "LuQingMei" },
    { "孟桂兰", "MengGuiLan" },
    { "宁雪琳", "NingXueLin" },
    { "潘银萍", "PanYinPing" },
    { "孙美", "HaiKuoTianKong" },
    { "谭玉萍", "TanYuPing" },
    { "王博", "WangBo" },
    { "王迪", "WangDi" },
    { "王凯", "WangKai" },
    { "王亮娟", "WangLiangJuan" },
    { "王立梅", "WangLiMei" },
    { "王勇勇", "WangYongYong" },
    { "王子林", "WangZiLin" },
    { "魏龙豪", "WeiLongHao" },
    { "吴超群", "WuChaoQun" },
    { "吴前前", "WuQianQian" },
    { "解加秀", "XieJiaXiu" },
    { "杨泽晨", "YangZeChen" },
    { "闫云", "YanYun" },
    { "于冲", "YuChong" },
    { "张海洋", "ZhangHaiYang" },
    { "战立琪", "ZhanLiQi" },
    { "祝艳雨", "ZhuYanYu" },
    { "常丽霞", "ChangLiXia" },
    { "高华玲", "GaoHuaLing" },
    { "关秀娟", "GuanXiuJuan" },
    { "韩锡乾", "HanXiQian" },
    { "胡雪", "HuXue" },
    { "纪蕾", "JiLei" },
    { "李丽莎", "LiLiSha" },
    { "林庆梅", "LinQingMei" },
    { "刘兰", "LiuLan" },
    { "刘庆", "LiuQing" },
    { "刘顺霞", "LiuShunXia" },
    { "刘钊聚", "LiuZhaoJu" },
    { "李阳", "YuanJin" },
    { "马彦姣", "MaYanJiao" },
    { "孟繁帅", "MengFanShuai" },
    { "孙丰丰", "SunFengFeng" },
    { "孙宜兰", "SunYiLan" },
    { "王宏亮", "WangHongLiang" },
    { "王茂桢", "WangMaoZhen" },
    { "徐鑫杰", "XuXinJie" },
    { "张花", "ZhangHua" },
    { "张小梅", "JianDan" },
    { "张月凌", "ZhangYueLing" },
    { "周燕", "ZhouYan" },
    { "薛冰坤", "3fbd4f55dad6fd7a20df3007bf66359a" },
    { "张洪建", "ZhangHongJian" },
    { "陈代云", "ChenDaiYun" },
    { "陈旭斌", "ChenXuBin" },
    { "管玉霞", "GuanYuXia" },
    { "侯祥涛", "HouXiangTao" },
    { "胡丽华", "HuLiHua" },
    { "李杰", "LiJie" },
    { "李亮亮", "LiLiangLiang" },
    { "柳丽丽", "LiuLiLi" },
    { "刘利霞", "LiuLiXia" },
    { "刘岩", "LiuYan" },
    { "刘毅", "LiuYi" },
    { "刘芷硕", "LiuZhiShuo" },
    { "马一原", "MaYiYuan" },
    { "商丽", "ShangLi" },
    { "邵娅函", "ShaoYaHan" },
    { "申有竹", "ShenYouZhu" },
    { "孙丹华", "SunDanHua" },
    { "孙双城", "SunShuangCheng" },
    { "孙泽智", "SunZeZhi" },
    { "佟志学", "TongZhiXue" },
    { "魏莹莹", "WeiYingYing" },
    { "吴秋连", "WuQiuLian" },
    { "吴祥晨", "WuXiangChen" },
    { "仙玉霞", "XianYuXia" },
    { "肖帅", "XiaoShuai" },
    { "徐艳君", "XuYanJun" },
    { "尹红", "YinHong" },
    { "于凤妹", "YuFengMei" },
    { "张晶", "ZhangJing" },
    { "张梅梅", "ZhangMeiMei" },
    { "张璇", "ZhangXuan" },
    { "赵子祥", "ZhaoZiXiang" },
    { "庄自超", "ZhuangZiChao" },
    { "朱珮瑜", "ZhuPeiYu" },
    { "柴慧敏", "ChaiHuiMin" },
    { "江红睿", "JiangHongRui" },
    { "李军焕", "LiJunHuan" },
    { "刘俊江", "LiuJunJiang" },
    { "邱龙飞", "QiuLongFei" },
    { "孙泽政", "SunZeZheng" },
    { "王宏顺", "WangHongShun" },
    { "吴超宇", "WuChaoYu" },
    { "肖镇营", "XiaoZhenYing" },
    { "夏宇", "XiaYu" },
    { "徐培钦", "XuPeiQin" },
    { "张颖祺", "ZhangYingQi" },
    { "陈晓霞", "ChenXiaoXia" },
    { "付美华", "FuMeiHua" },
    { "高晓冬", "GaoXiaoDong" },
    { "季艳玲", "JiYanLing" },
    { "刘翠凤", "LiuCuiFeng" },
    { "秦绪英", "QinXuYing" },
    { "宋晓莉", "SongXiaoLi" },
    { "于东森", "YuDongSen" },
    { "于海淼", "ericman" },
    { "胡宗亮", "HuZongLiang" },
    { "黄梓敖", "HuangZiAo" },
    { "刘湘龙", "LiuXiangLong" },
    { "刘学伟", "LiuXueWei" },
    { "王正盛", "WangZhengSheng" },
    { "吴亚慧", "WuYaHui" },
    { "勾文哲", "GouWenZhe" },
    { "韩建烁", "HanJianShuo" },
    { "姜怡帆", "JiangYiFan" },
    { "冷健", "LengJian" },
    { "廉凯华", "LianKaiHua" },
    { "李美锌", "LiMeiXin" },
    { "林本宝", "LinBenBao" },
    { "李玉锋", "LiYuFeng1" },
    { "孙吉傲", "SunJiAo" },
    { "王宝", "WangBao" },
    { "王继朋", "WangJiPeng" },
    { "魏书浩", "WeiShuHao" },
    { "徐东", "XuDong" },
    { "徐云飞", "XuYunFei" },
    { "张兵", "ZhangBing" },
    { "孟聪颖", "MengCongYing" },
    { "徐可", "XuKe1" },
    { "陈珮珮", "ChenPeiPei" },
    { "李芳泽", "LiFangZe" },
    { "殷秀芬", "YinXiuFen" },
    { "苏志东", "SuZhiDong" },
    { "郭燕霞", "GuoYanXia" },
    { "彭妍", "PengYan" },
    { "孙晓艳", "XueEr" },
    { "徐海花", "XuHaiHua" },
    { "周晨", "ZhouChen" },
    { "冯嘉馨", "FengJiaXin" },
    { "李琦琦", "LiQiQi" },
    { "李珍珍", "LiZhenZhen" },
    { "宋春蕾", "SongChunLei" },
    { "宋米岍玥", "SongMiQianYue" },
    { "赵小华", "ZhaoXiaoHua" },
    { "盛世玲", "ShengShiLing1" },
    { "韩瑜", "HanYu" },
    { "刘方星", "ShanQingShuiXiu" },
    { "苗本泰", "MiaoBenTai" },
    { "王振旭", "WangZhenXu" },
    { "谢昆仑", "XieKunLun" },
    { "赵子彤", "ZhaoZiTong" },
    { "徐文汇", "XuWenHui" },
    { "王珑儒", "WangLongRu" },
    { "司玉琨", "SiYuKun" },
    { "李祥付", "LiXiangFu" },
    { "牛兆学", "NiuZhaoXue" },
    { "盛大成", "ShengDaCheng" },
    { "王振", "WangZhen" },
    { "陈晓", "ChenXiao" },
    { "李全", "LiQuan" },
    { "刘骏", "LiuJun_1" },
    { "刘克先", "LiuKeXian" },
    { "信息中心运维公共账号", "XinXiZhongXinYunWeiGongGongZhang" },
    { "杨威", "YangWei" },
    { "俞超", "YuChao" },
    { "王松松", "WangSongSong" },
    { "陈玉平", "ChenYuPing" },
    { "李家斌", "LiJiaBin" },
    { "王帅旗", "WangShuaiQi" },
    { "彭朱容", "PengZhuRong" },
    { "高得利", "GaoDeLi" },
    { "刘佰香", "LiuBaiXiang" },
    { "刘东", "LiuDong" },
    { "宋国祯", "SongGuoZhen" },
    { "王苗", "WangMiao" },
    { "温阳阳", "WenYangYang" },
    { "徐广苓", "ChenBaoBei" },
    { "徐世鹏", "XuShiPeng" },
    { "赵玉超", "ZhaoYuChao" },
    { "钟艳霞", "ZhongYanXia" },
    { "李连凯", "LiLianKai" },
    { "王明浩", "WangMingHao" },
    { "庄志峰", "ZhuangZhiFeng" },
    { "苟方越", "GouFangYue" }
};


        /// <summary>
        /// 根据中文姓名获取企微用户名
        /// </summary>
        /// <param name="chineseName">中文姓名</param>
        /// <returns>
        /// 企微用户名，如果映射不存在则返回null
        /// </returns>
        public static string GetWeComUser(string chineseName)
        {
            if (string.IsNullOrWhiteSpace(chineseName))
                return null;

            // 支持多个用户用"|"分隔
            if (chineseName.Contains("|"))
            {
                var names = chineseName.Split('|');
                var users = new List<string>();
                foreach (var name in names)
                {
                    var user = GetSingleUser(name.Trim());
                    if (user == null)
                        return null; // 任何一个用户映射失败则整体失败
                    users.Add(user);
                }
                return string.Join("|", users);
            }

            return GetSingleUser(chineseName);
        }

        /// <summary>
        /// 获取单个用户的企微用户名
        /// </summary>
        /// <param name="chineseName">中文姓名</param>
        /// <returns>企微用户名，如果不存在则返回null</returns>
        private static string GetSingleUser(string chineseName)
        {
            if (string.IsNullOrWhiteSpace(chineseName))
                return null;

            return UserMap.TryGetValue(chineseName, out var wecomUser) ? wecomUser : null;
        }

        /// <summary>
        /// 检查用户映射是否存在
        /// </summary>
        /// <param name="chineseName">中文姓名</param>
        /// <returns>是否存在映射</returns>
        public static bool HasMapping(string chineseName)
        {
            return GetWeComUser(chineseName) != null;
        }
    }
}